package py.com.icarusdb.agenda.model.client;

import py.com.icarusdb.agenda.model.Auditoria;

public interface AuditoriaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditoria
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    int insert(Auditoria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditoria
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    int insertSelective(Auditoria record);
}