package py.com.icarusdb.agenda.model.client;

import java.util.List;

import py.com.icarusdb.agenda.model.Cargo;

public interface CargoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    int insert(Cargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    int insertSelective(Cargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    Cargo selectByPrimaryKey(Long id);
    
    List<Cargo> selectAllActive();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    int updateByPrimaryKeySelective(Cargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cargo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    int updateByPrimaryKey(Cargo record);

    List<Cargo> selectAllOrderedByName();
}