package py.com.icarusdb.agenda.model.client;

import py.com.icarusdb.agenda.model.Empleado;

public interface EmpleadoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empleado
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empleado
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    int insert(Empleado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empleado
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    int insertSelective(Empleado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empleado
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    Empleado selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empleado
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    int updateByPrimaryKeySelective(Empleado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empleado
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    int updateByPrimaryKey(Empleado record);
}