package py.com.icarusdb.agenda.model;

import java.util.Date;

public class Auditoria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditoria.fecha
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Date fecha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditoria.accion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String accion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditoria.descripcion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String descripcion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auditoria.ip_address
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String ipAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditoria.fecha
     *
     * @return the value of auditoria.fecha
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditoria.fecha
     *
     * @param fecha the value for auditoria.fecha
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditoria.accion
     *
     * @return the value of auditoria.accion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getAccion() {
        return accion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditoria.accion
     *
     * @param accion the value for auditoria.accion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setAccion(String accion) {
        this.accion = accion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditoria.descripcion
     *
     * @return the value of auditoria.descripcion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditoria.descripcion
     *
     * @param descripcion the value for auditoria.descripcion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auditoria.ip_address
     *
     * @return the value of auditoria.ip_address
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auditoria.ip_address
     *
     * @param ipAddress the value for auditoria.ip_address
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
}