package py.com.icarusdb.agenda.model;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class Cargo
{
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column cargo.id
     * 
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column cargo.activo
     * 
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Boolean activo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column cargo.descripcion
     * 
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String descripcion;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column cargo.id
     * 
     * @return the value of cargo.id
     * 
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Long getId()
    {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cargo.id
     * 
     * @param id
     *            the value for cargo.id
     * 
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setId(Long id)
    {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column cargo.activo
     * 
     * @return the value of cargo.activo
     * 
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Boolean getActivo()
    {
        return activo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cargo.activo
     * 
     * @param activo
     *            the value for cargo.activo
     * 
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setActivo(Boolean activo)
    {
        this.activo = activo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column cargo.descripcion
     * 
     * @return the value of cargo.descripcion
     * 
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getDescripcion()
    {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column cargo.descripcion
     * 
     * @param descripcion
     *            the value for cargo.descripcion
     * 
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setDescripcion(String descripcion)
    {
        this.descripcion = descripcion;
    }
}