package py.com.icarusdb.agenda.model;

import java.util.Date;

public class Dependencia {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dependencia.id
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dependencia.activo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Boolean activo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dependencia.fecha_creacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Date fechaCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dependencia.nombre_dependencia
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String nombreDependencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dependencia.sigla
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String sigla;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dependencia.usuario_creacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String usuarioCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dependencia.id_dependencia_padre
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Long idDependenciaPadre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dependencia.id
     *
     * @return the value of dependencia.id
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dependencia.id
     *
     * @param id the value for dependencia.id
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dependencia.activo
     *
     * @return the value of dependencia.activo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Boolean getActivo() {
        return activo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dependencia.activo
     *
     * @param activo the value for dependencia.activo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dependencia.fecha_creacion
     *
     * @return the value of dependencia.fecha_creacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dependencia.fecha_creacion
     *
     * @param fechaCreacion the value for dependencia.fecha_creacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dependencia.nombre_dependencia
     *
     * @return the value of dependencia.nombre_dependencia
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getNombreDependencia() {
        return nombreDependencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dependencia.nombre_dependencia
     *
     * @param nombreDependencia the value for dependencia.nombre_dependencia
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setNombreDependencia(String nombreDependencia) {
        this.nombreDependencia = nombreDependencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dependencia.sigla
     *
     * @return the value of dependencia.sigla
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getSigla() {
        return sigla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dependencia.sigla
     *
     * @param sigla the value for dependencia.sigla
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dependencia.usuario_creacion
     *
     * @return the value of dependencia.usuario_creacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getUsuarioCreacion() {
        return usuarioCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dependencia.usuario_creacion
     *
     * @param usuarioCreacion the value for dependencia.usuario_creacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dependencia.id_dependencia_padre
     *
     * @return the value of dependencia.id_dependencia_padre
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Long getIdDependenciaPadre() {
        return idDependenciaPadre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dependencia.id_dependencia_padre
     *
     * @param idDependenciaPadre the value for dependencia.id_dependencia_padre
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setIdDependenciaPadre(Long idDependenciaPadre) {
        this.idDependenciaPadre = idDependenciaPadre;
    }
}