package py.com.icarusdb.agenda.model;

import java.util.Date;

public class Empleado {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.id
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.ci
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String ci;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.ciudad
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String ciudad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.codigopostal
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String codigopostal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.contrasena
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String contrasena;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.direccion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String direccion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.email
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.estado
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String estado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.fecha_creacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Date fechaCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.fecha_nacimiento
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Date fechaNacimiento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.nombre_apellido
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String nombreApellido;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.nro_celular
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String nroCelular;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.nro_celular_corporativo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String nroCelularCorporativo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.nro_interno
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String nroInterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.nro_plaqueta
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Integer nroPlaqueta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.nro_telefono
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String nroTelefono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.titulo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String titulo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.usuario
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String usuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.usuario_creacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String usuarioCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.id_cargo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Long idCargo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.id_dependencia
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private Long idDependencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.alergico_a
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String alergicoA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.urgencia_comunicacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String urgenciaComunicacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.email_corporativo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String emailCorporativo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empleado.grupo_sanguineo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    private String grupoSanguineo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.id
     *
     * @return the value of empleado.id
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.id
     *
     * @param id the value for empleado.id
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.ci
     *
     * @return the value of empleado.ci
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getCi() {
        return ci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.ci
     *
     * @param ci the value for empleado.ci
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setCi(String ci) {
        this.ci = ci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.ciudad
     *
     * @return the value of empleado.ciudad
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getCiudad() {
        return ciudad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.ciudad
     *
     * @param ciudad the value for empleado.ciudad
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.codigopostal
     *
     * @return the value of empleado.codigopostal
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getCodigopostal() {
        return codigopostal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.codigopostal
     *
     * @param codigopostal the value for empleado.codigopostal
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setCodigopostal(String codigopostal) {
        this.codigopostal = codigopostal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.contrasena
     *
     * @return the value of empleado.contrasena
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getContrasena() {
        return contrasena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.contrasena
     *
     * @param contrasena the value for empleado.contrasena
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.direccion
     *
     * @return the value of empleado.direccion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.direccion
     *
     * @param direccion the value for empleado.direccion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.email
     *
     * @return the value of empleado.email
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.email
     *
     * @param email the value for empleado.email
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.estado
     *
     * @return the value of empleado.estado
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.estado
     *
     * @param estado the value for empleado.estado
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.fecha_creacion
     *
     * @return the value of empleado.fecha_creacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.fecha_creacion
     *
     * @param fechaCreacion the value for empleado.fecha_creacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.fecha_nacimiento
     *
     * @return the value of empleado.fecha_nacimiento
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.fecha_nacimiento
     *
     * @param fechaNacimiento the value for empleado.fecha_nacimiento
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.nombre_apellido
     *
     * @return the value of empleado.nombre_apellido
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getNombreApellido() {
        return nombreApellido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.nombre_apellido
     *
     * @param nombreApellido the value for empleado.nombre_apellido
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setNombreApellido(String nombreApellido) {
        this.nombreApellido = nombreApellido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.nro_celular
     *
     * @return the value of empleado.nro_celular
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getNroCelular() {
        return nroCelular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.nro_celular
     *
     * @param nroCelular the value for empleado.nro_celular
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setNroCelular(String nroCelular) {
        this.nroCelular = nroCelular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.nro_celular_corporativo
     *
     * @return the value of empleado.nro_celular_corporativo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getNroCelularCorporativo() {
        return nroCelularCorporativo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.nro_celular_corporativo
     *
     * @param nroCelularCorporativo the value for empleado.nro_celular_corporativo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setNroCelularCorporativo(String nroCelularCorporativo) {
        this.nroCelularCorporativo = nroCelularCorporativo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.nro_interno
     *
     * @return the value of empleado.nro_interno
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getNroInterno() {
        return nroInterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.nro_interno
     *
     * @param nroInterno the value for empleado.nro_interno
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setNroInterno(String nroInterno) {
        this.nroInterno = nroInterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.nro_plaqueta
     *
     * @return the value of empleado.nro_plaqueta
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Integer getNroPlaqueta() {
        return nroPlaqueta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.nro_plaqueta
     *
     * @param nroPlaqueta the value for empleado.nro_plaqueta
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setNroPlaqueta(Integer nroPlaqueta) {
        this.nroPlaqueta = nroPlaqueta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.nro_telefono
     *
     * @return the value of empleado.nro_telefono
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getNroTelefono() {
        return nroTelefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.nro_telefono
     *
     * @param nroTelefono the value for empleado.nro_telefono
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setNroTelefono(String nroTelefono) {
        this.nroTelefono = nroTelefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.titulo
     *
     * @return the value of empleado.titulo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getTitulo() {
        return titulo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.titulo
     *
     * @param titulo the value for empleado.titulo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.usuario
     *
     * @return the value of empleado.usuario
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.usuario
     *
     * @param usuario the value for empleado.usuario
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.usuario_creacion
     *
     * @return the value of empleado.usuario_creacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getUsuarioCreacion() {
        return usuarioCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.usuario_creacion
     *
     * @param usuarioCreacion the value for empleado.usuario_creacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.id_cargo
     *
     * @return the value of empleado.id_cargo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Long getIdCargo() {
        return idCargo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.id_cargo
     *
     * @param idCargo the value for empleado.id_cargo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setIdCargo(Long idCargo) {
        this.idCargo = idCargo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.id_dependencia
     *
     * @return the value of empleado.id_dependencia
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public Long getIdDependencia() {
        return idDependencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.id_dependencia
     *
     * @param idDependencia the value for empleado.id_dependencia
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setIdDependencia(Long idDependencia) {
        this.idDependencia = idDependencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.alergico_a
     *
     * @return the value of empleado.alergico_a
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getAlergicoA() {
        return alergicoA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.alergico_a
     *
     * @param alergicoA the value for empleado.alergico_a
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setAlergicoA(String alergicoA) {
        this.alergicoA = alergicoA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.urgencia_comunicacion
     *
     * @return the value of empleado.urgencia_comunicacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getUrgenciaComunicacion() {
        return urgenciaComunicacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.urgencia_comunicacion
     *
     * @param urgenciaComunicacion the value for empleado.urgencia_comunicacion
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setUrgenciaComunicacion(String urgenciaComunicacion) {
        this.urgenciaComunicacion = urgenciaComunicacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.email_corporativo
     *
     * @return the value of empleado.email_corporativo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getEmailCorporativo() {
        return emailCorporativo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.email_corporativo
     *
     * @param emailCorporativo the value for empleado.email_corporativo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setEmailCorporativo(String emailCorporativo) {
        this.emailCorporativo = emailCorporativo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empleado.grupo_sanguineo
     *
     * @return the value of empleado.grupo_sanguineo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public String getGrupoSanguineo() {
        return grupoSanguineo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empleado.grupo_sanguineo
     *
     * @param grupoSanguineo the value for empleado.grupo_sanguineo
     *
     * @mbggenerated Tue Sep 10 14:19:39 PYT 2013
     */
    public void setGrupoSanguineo(String grupoSanguineo) {
        this.grupoSanguineo = grupoSanguineo;
    }
}